enum routes {
  HOME_TAB = "HomeTab",
  HOME = "Home",
  LOGIN = "Login",
  REGISTER = "Register",
  CHANGE_PASSWORD = "ChangePassword",
  RESET_PASSWORD = "ResetPassword",
  RESET_PASSWORD_OTP = "ResetPasswordOTP",
  LOGIN_INTERMEDIATE = "LoginIntermediate",
  UPDATE_USER = "UpdateUser",
  NOTIFICATIONS = "Notifications",
  WELCOME = "Welcome",
  SETTINGS = "Settings",
  LOGIN_OTP = "OTP",
  USER_PROFILE = "UserProfile",
  FIND_SCRIBE = "FindScribe",
  ABOUT = "About",
  TUTORIALS = "Tutorials",
  THREE_D_SCANNER_MODEL_DETAILS = "ThreeDScannerModelDetails",
  SHARE_APP = "ShareAppScreen",
  ROOM_LIST = "RoomList",
  DIRECTIONS = "Directions",
  HISTORY = "History",
}

export default routes;
